### ISSUE TITLE
other examples, avoiding repeat work

### ISSUE THREAD

**Issue by j---** [agogeio/crypteia#1]
Hi!
Have you seen any of the following? Should any of these efforts merge? 

https://github.com/theparanoids/PrioritizedRiskRemediation
https://www.linkedin.com/posts/patrickmgarrity_a-guide-to-automating-vulnerability-prioritization-activity-7087527275583205376-fobq
https://stephenshaffer.io/flipping-the-vulnerability-management-model-cvss-ssvc-aaa78f1426e1
https://github.com/CERTCC/labyrinth

**Comment by agogeio** [comment]
I actually know Patrick Garrity pretty well, we live close to each other; I haven't seen the others.  This whole project started off as a way for me to learn the Pandas library better but it took on a life of it's own. Thank you very much for sending these over.
